apiVersion: v1
kind: ConfigMap
metadata:
  name: marketplace-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-0.postgres-service.default.svc.cluster.local:5432/marketplace"
  SPRING_REDIS_HOST: "redis-0.redis-service.default.svc.cluster.local"
  SPRING_REDIS_PORT: "6379"
  SPRING_AUTOCONFIGURE_EXCLUDE: "org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration"
  APP_FEIGN-CLIENT_URL: "http://rate-service.default.svc.cluster.local:8080"
  APP_JSON_PATH: "/resources/json/dollar_exchange_rate.json"
