spring.application.name: marketplace

spring:
  kafka:
    listener:
      header:
        mapper: default
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: consumer-group
      properties:
        spring.json.trusted.packages: com.*
        spring.json.value.default.type: "com.spring.marketplace.events.EventSource"
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
     password: ILin47gim
     username: postgres
     url: jdbc:postgresql://localhost:5432/marketplace
     driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6378
    time-to-live: 10

app:
  default:
    rate-value: 1
  scheduling:
    period: 30000
    enabled: false
  file:
    path: C:\\marketplace\\marketplace\\src\\main\\resources\\reports\\
  download-upload:
    path: C:\\marketplace\\marketplace\\src\\main\\resources\\files\\
  json:
    path: C:\marketplace\marketplace\src\main\resources\json\\dollar_exchange_rate.json
  feign-client:
    rate-service:
         url: http://localhost:8080/
    mail-service:
         url: http://localhost:8085/
  kafka:
    topic:
      name: events

server.port: 0

