spring.application.name: mail-service

spring:
  cloud:
    config:
      enabled: false
  datasource:
    password: ILin47gim
    username: postgres
    url: jdbc:postgresql://localhost:5432/marketplace
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server.port: 8085

eureka:
  client:
    enabled: false