name: Marketplace CI/CD Pipeline

# Build stages
# - Build
# - Test
# - Deploy

on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Setup Java and Maven environment
        uses: ./.github/actions/setup
      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- Build Marketplace API ---
      - name: Build Marketplace Api
        uses: ./.github/actions/build
        with:
          service-path: '.'
          docker-image-name: 'api'

      # --- Build Rate API ---
      - name: Build Rate Api
        uses: ./.github/actions/build
        with:
          service-path: 'rate-service'
          docker-image-name: 'rate'

      # --- Build Mail API ---
      - name: Build Mail Api
        uses: ./.github/actions/build
        with:
          service-path: 'mail-service'
          docker-image-name: 'mail'

  test:
    runs-on: self-hosted
    needs: build
    steps:
      ## Setup
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Setup Java and Maven environment
        uses: ./.github/actions/setup
      - name: Run docker container for tests
        env :
          POSTGRES_USERNAME_TEST: ${{ secrets.POSTGRES_USERNAME_TEST }}
          POSTGRES_PASSWORD_TEST: ${{ secrets.POSTGRES_PASSWORD_TEST }}
        run : docker-compose -f ./.github/test/docker-test.yml up -d
      - name: Copy Json rate
        run : mkdir -p ./resources/json && cp -R ./src/main/resources/json/* ./resources/json/
      - name: Install Yq
        run : snap install yq
      - name: Update JSON path in application-test.yml
        run : yq -i '.app.json.path = "./resources/json/dollar_exchange_rate.json"' ./src/test/resources/application-test.yml

      ##Run tests
      - name: Run Marketplace API Tests
        run : mvn test -Dspring.profiles.active=test
      - name: Run Rate API Tests
        run : cd rate-service && mvn test
      - name: Run Mail API Tests
        run : cd mail-service && mvn test
      - name: Delete postgres test container
        run : docker rm -f test

  deploy:
    runs-on: self-hosted
    needs:
      - build
      - test
    steps:
      - name: Docker image prune
        run: docker image prune
      - name: Check cluster info
        run : kubectl cluster-info
      - name: Apply K8s files
        run : kubectl apply -f k8s/ -R

